before_install:
  - chmod +x mvnw
language: java 
cache:
- $HOME/.m2
sudo: required
image_tag: 
- latest
jdk:
- oraclejdk8
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package
- docker build -t r0623646/dacontinuousdeployment:latest
- docker push r0623646/dacontinuousdeployment:latest
